/** Theme-aware Tailwind class bundles for Discover & Request UI. */
export const discoveryTheme = {
    heading: 'text-2xl font-black text-text tracking-tight',
    subheading: 'text-sm text-muted mt-1',
    sectionTitle: 'text-xl font-bold text-text',
    tabBar: 'border-b border-border',
    tab: 'flex items-center gap-2 pb-4 border-b-2 font-bold transition-all whitespace-nowrap border-transparent text-muted hover:text-text/80',
    tabActive: 'border-plex text-text',
    toolbarBtn: 'flex items-center gap-2 px-4 py-2 bg-white/5 border border-border hover:bg-white/10 rounded-lg text-text/80 hover:text-text font-bold transition-colors',
    mobileNavBtn: 'w-full flex items-center justify-between p-3 rounded-lg bg-white/5 border border-border text-text font-bold',
    mobileNavMenu: 'absolute top-full left-0 right-0 mt-2 bg-card border border-border rounded-lg shadow-xl overflow-hidden z-50',
    mobileNavItem: 'w-full flex items-center gap-2 p-3 text-left hover:bg-white/5 text-muted',
    mobileNavItemActive: 'text-text bg-white/5',
    filterChip: 'inline-flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-bold border transition-colors bg-white/[0.03] border-border text-muted hover:text-text hover:border-border',
    filterChipActive: 'bg-plex/15 border-plex/40 text-text',
    filterChipCount: 'text-[11px] px-1.5 py-0.5 rounded-full bg-white/5 text-muted',
    filterChipCountActive: 'bg-plex/20 text-plex',
    emptyState: 'rounded-xl border border-border bg-white/[0.03] px-6 py-12 text-center',
    emptyTitle: 'text-text/80 font-semibold',
    emptyBody: 'text-sm text-muted mt-2',
    searchInput: 'w-full bg-background/60 border-2 border-border focus:border-plex rounded-xl py-3.5 sm:py-4 pl-12 sm:pl-14 pr-12 text-base sm:text-lg text-text font-medium outline-none transition-all placeholder:text-muted/50 shadow-inner',
    searchDropdown: 'max-h-[min(420px,50vh)] overflow-y-auto custom-scrollbar rounded-xl border border-border bg-card shadow-2xl',
    searchResultBtn: 'w-full flex items-center gap-4 p-3 hover:bg-white/[0.06] border-b border-border last:border-0 text-left transition-colors bg-card',
    heroShell: 'relative w-full rounded-2xl border border-border shadow-2xl min-h-[220px] sm:min-h-[280px] overflow-visible',
    heroBackdrop: 'absolute inset-0 rounded-2xl overflow-hidden bg-gradient-to-br from-plex/20 to-background/80',
    heroTitle: 'text-2xl sm:text-4xl font-bold text-text tracking-tight drop-shadow-md',
    drawerOverlay: 'fixed inset-0 bg-background/80 backdrop-blur-sm z-[100] transition-opacity duration-300',
    drawerPanel: 'fixed top-0 right-0 h-full w-full max-w-[440px] bg-card border-l border-border z-[101] shadow-2xl flex flex-col transition-transform duration-500 ease-[cubic-bezier(0.32,0.72,0,1)]',
    drawerHeader: 'flex items-center justify-between p-6 border-b border-border bg-background/20',
    drawerTitle: 'text-2xl font-black text-text tracking-tight flex items-center gap-3',
    posterEmpty: 'flex flex-col items-center justify-center py-16 px-6 rounded-2xl border border-dashed border-border bg-white/[0.02] text-center',
};
