/**
 * Default notification templates (Phase 2–3 / #89).
 * Placeholders: {title} {user} {media_type} {request_label} {status} {portal_url} {year}
 * {season} {server_name} {decline_reason} {filename} {service} {service_mark}
 */

export const NOTIFY_EVENTS = [
    'available',
    'approved',
    'declined',
    'season',
    'episode',
    'admin_pending',
    'not_released',
    'collexions_failed',
    'spotify_sync_failed',
    'scanner_failed',
    'scanner_deleted',
    'scanner_upgrade',
    'scanner_import',
    'scanner_grab',
    'scanner_update',
    'scanner_interaction',
    'status_down',
    'status_up',
    'media_job_failed',
    'media_job_completed',
    'support_ticket',
    'support_reply',
    'support_media_issue',
];

export const NOTIFY_TEMPLATE_FIELDS = [
    'emailSubject',
    'emailHeadline',
    'emailBody',
    'pushTitle',
    'pushBody',
    'discordContent',
    'discordEmbedTitle',
    'discordEmbedDescription',
    'gotifyTitle',
    'gotifyBody',
    'ntfyTitle',
    'ntfyBody',
    'webhookBody',
];

/** Fields shown in the admin editor per event. */
export const NOTIFY_EVENT_FIELDS = {
    available: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
        'discordContent', 'discordEmbedTitle', 'discordEmbedDescription',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    approved: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    declined: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    season: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    episode: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    admin_pending: [
        'pushTitle', 'pushBody',
        'gotifyTitle', 'gotifyBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    not_released: [
        'emailSubject', 'emailHeadline', 'emailBody',
        'pushTitle', 'pushBody',
    ],
    collexions_failed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    spotify_sync_failed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_failed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_deleted: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_upgrade: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_import: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_grab: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_update: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    scanner_interaction: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    status_down: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    status_up: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    media_job_failed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    media_job_completed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    tautulli_api_failed: [
        'pushTitle', 'pushBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    support_ticket: [
        'pushTitle', 'pushBody',
        'gotifyTitle', 'gotifyBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    support_reply: [
        'pushTitle', 'pushBody',
        'gotifyTitle', 'gotifyBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
    support_media_issue: [
        'pushTitle', 'pushBody',
        'gotifyTitle', 'gotifyBody',
        'ntfyTitle', 'ntfyBody',
        'webhookBody',
    ],
};

export const DEFAULT_NOTIFY_TEMPLATES = {
    available: {
        emailSubject: '[{server_name}] {title} is now available',
        emailHeadline: 'Your request is available',
        emailBody: 'Good news — the {media_type} you requested is ready to watch on the server.',
        pushTitle: '{title} is available',
        pushBody: 'Your request for {title} is ready to watch.',
        discordContent: '**{title}{year}** is now available — requested by **{user}**.',
        discordEmbedTitle: '{title}{year}',
        discordEmbedDescription: 'The {media_type} is ready to watch.',
        ntfyTitle: '{title} is available',
        ntfyBody: 'Requested by {user}. Ready to watch.',
        webhookBody: '',
    },
    approved: {
        emailSubject: '[{server_name}] Your request was approved: {title}',
        emailHeadline: 'Your request was approved',
        emailBody: 'An admin approved your request. We will notify you again when it is available.',
        pushTitle: 'Approved: {title}',
        pushBody: 'Your request for {title} has been approved.',
        ntfyTitle: 'Approved: {title}',
        ntfyBody: 'Your request for {title} has been approved.',
        webhookBody: '',
    },
    declined: {
        emailSubject: '[{server_name}] Your request was declined: {title}',
        emailHeadline: 'Your request was declined',
        emailBody: 'An admin declined your request.{decline_reason}',
        pushTitle: 'Declined: {title}',
        pushBody: 'Your request for {title} was declined.',
        ntfyTitle: 'Declined: {title}',
        ntfyBody: 'Your request for {title} was declined.{decline_reason}',
        webhookBody: '',
    },
    season: {
        emailSubject: '[{server_name}] {season} of {title} is available',
        emailHeadline: 'A season is available',
        emailBody: '{season} of the series you requested is ready to watch.',
        pushTitle: '{season} of {title} is available',
        pushBody: '{season} of {title} is ready to watch.',
        ntfyTitle: '{season} of {title} is available',
        ntfyBody: 'A requested season is ready to watch.',
        webhookBody: '',
    },
    episode: {
        emailSubject: '[{server_name}] New episode: {title}',
        emailHeadline: 'New episode available',
        emailBody: 'New episode(s) arrived for a series you requested.',
        pushTitle: 'New episode: {title}',
        pushBody: 'New episode(s) arrived for {title}.',
        ntfyTitle: 'New episode: {title}',
        ntfyBody: 'New episode(s) arrived for your series.',
        webhookBody: '',
    },
    admin_pending: {
        pushTitle: 'New media request',
        pushBody: '{request_label}: {title}{year} [{user}]',
        gotifyTitle: 'New media request',
        gotifyBody: '{request_label}: {title}{year} [{user}]',
        ntfyTitle: 'New media request',
        ntfyBody: '{request_label}: {title}{year} [{user}]',
        webhookBody: '{request_label}: {title}{year} [{user}]',
    },
    not_released: {
        emailSubject: '[{server_name}] {title} isn’t released yet',
        emailHeadline: 'Not released yet',
        emailBody: 'Thanks for requesting {title}. It isn’t out yet — expected {release_type}: {release_date}. We’ll notify you when it’s available.',
        pushTitle: '{title} isn’t released yet',
        pushBody: '{release_type}: {release_date}. We’ll notify you when it’s available.',
    },
    collexions_failed: {
        pushTitle: 'ColleXions failed',
        pushBody: '{title}',
        ntfyTitle: 'ColleXions failed',
        ntfyBody: '{title}',
        webhookBody: '',
    },
    spotify_sync_failed: {
        pushTitle: 'Spotify Sync failed',
        pushBody: '{title}',
        ntfyTitle: 'Spotify Sync failed',
        ntfyBody: '{title}',
        webhookBody: '',
    },
    scanner_failed: {
        pushTitle: 'Scanner failed',
        pushBody: '{title}',
        ntfyTitle: 'Scanner failed',
        ntfyBody: '{title}',
        webhookBody: '',
    },
    scanner_deleted: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Deleted: {title}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Deleted: {title}',
        webhookBody: '',
    },
    scanner_upgrade: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Upgraded: {title}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Upgraded: {title}',
        webhookBody: '',
    },
    scanner_import: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Imported: {title}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Imported: {title}',
        webhookBody: '',
    },
    scanner_grab: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Grabbed: {filename}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Grabbed: {filename}',
        webhookBody: '',
    },
    scanner_update: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Updated: {title}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Updated: {title}',
        webhookBody: '',
    },
    scanner_interaction: {
        pushTitle: 'Scanner Notification [{service}]',
        pushBody: '{service_mark}Needs attention: {filename}',
        ntfyTitle: 'Scanner Notification [{service}]',
        ntfyBody: '{service_mark}Needs attention: {filename}',
        webhookBody: '',
    },
    status_down: {
        pushTitle: '{title} is down',
        pushBody: 'A health check has been down longer than the configured wait.',
        ntfyTitle: '{title} is down',
        ntfyBody: 'Health check has been down longer than the configured wait.',
        webhookBody: '',
    },
    status_up: {
        pushTitle: '{title} is back up',
        pushBody: 'The health check recovered.',
        ntfyTitle: '{title} is back up',
        ntfyBody: 'The health check recovered.',
        webhookBody: '',
    },
    media_job_failed: {
        pushTitle: 'Media Automation job failed',
        pushBody: '{title}',
        ntfyTitle: 'Media Automation job failed',
        ntfyBody: '{title}',
        webhookBody: '',
    },
    media_job_completed: {
        pushTitle: 'Media Automation job finished',
        pushBody: '{title}',
        ntfyTitle: 'Media Automation job finished',
        ntfyBody: '{title}',
        webhookBody: '',
    },
    tautulli_api_failed: {
        pushTitle: 'Tautulli API failed',
        pushBody: 'Check Media Stack → Tautulli URL and API key, then Test connection.',
        ntfyTitle: 'Tautulli API failed',
        ntfyBody: 'Check Media Stack → Tautulli URL and API key, then Test connection.',
        webhookBody: '',
    },
    support_ticket: {
        pushTitle: 'New support ticket',
        pushBody: '{user}: {title}',
        gotifyTitle: 'New support ticket',
        gotifyBody: '{user}: {title}\n{portal_url}',
        ntfyTitle: 'New support ticket',
        ntfyBody: '{user}: {title}',
        webhookBody: '',
    },
    support_reply: {
        pushTitle: 'Support ticket reply',
        pushBody: '{user} replied to “{title}”',
        gotifyTitle: 'Support ticket reply',
        gotifyBody: '{user} replied to “{title}”\n{portal_url}',
        ntfyTitle: 'Support ticket reply',
        ntfyBody: '{user} replied to “{title}”',
        webhookBody: '',
    },
    support_media_issue: {
        pushTitle: 'New media issue ticket',
        pushBody: '{user}: {title}',
        gotifyTitle: 'New media issue ticket',
        gotifyBody: '{user}: {title}\n{portal_url}',
        ntfyTitle: 'New media issue ticket',
        ntfyBody: '{user}: {title}',
        webhookBody: '',
    },
};

export default DEFAULT_NOTIFY_TEMPLATES;
